### ISSUE TITLE
NCLink incompatible?

### ISSUE THREAD

**Issue by Faulkal** [CreatureSurvive/PullToClear#1]
Went though my tweaks and this is what was causing the safe mode. 

iPhone8,2 10.2: 6968a20998840f94516c9e14fe1d18947270dcc8

The following process has crashed:

    /System/Library/CoreServices/SpringBoard.app/SpringBoard

Your product was determined to be the most likely cause:

    PullToClear
    (/Library/MobileSubstrate/DynamicLibraries/PullToClear.dylib)

Relevant files (e.g. crash log and syslog) are attached.

**Comment by CreatureSurvive** [comment]
As of version 0.3.1 PullToClear fully supports NCLink10. Thanks for the report!
